#!/usr/bin/env bash
# Download the citation lineage of Anthropic's "Emotion Concepts and their
# Function in a Large Language Model" (2604.07729), plus the 2026 papers that
# directly close its two self-declared gaps (single-model, linear assumption).
# Strictly deduped against research/papers/** and research/probe/papers/**:
#   2310.01405 Zou RepE            -> research/probe/papers/C2/
#   2511.18397 MacDiarmid          -> research/probe/papers/C1/ + research/papers/N4_*
#   2601.10387 Lu Assistant Axis   -> research/papers/assistant-axis-*
#   2507.21509 Persona Vectors     -> research/probe/papers/C2/
set -uo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAPERS="$BASE/papers/emotion-lineage-2608"
SUMMARY="$BASE/anthropic-emotion-concepts-2026-04/download-summary.md"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 research-survey/1.0"

declare -a ENTRIES=(
  # strand|vz-anchor|filename|url

  # L1 直接先行工作：情绪/情感表征的机制谱系
  "L1 lineage|R4/R12|linear-representations-of-sentiment-2310.15154.pdf|https://arxiv.org/pdf/2310.15154"
  "L1 lineage|R11/R12|ai-shares-emotion-across-languages-cultures-2506.13978.pdf|https://arxiv.org/pdf/2506.13978"
  "L1 lineage|R4/R9|do-llms-feel-emotion-circuits-discovery-control-2510.11328.pdf|https://arxiv.org/pdf/2510.11328"

  # L2 状态可解码且可因果操控：belief / user model
  "L2 decodable|R7/R11|language-models-represent-beliefs-of-self-and-others-2402.18496.pdf|https://arxiv.org/pdf/2402.18496"
  "L2 decodable|R11/R12|talktuner-dashboard-transparency-control-user-model-2406.07882.pdf|https://arxiv.org/pdf/2406.07882"

  # L3 行为侧来源：blackmail 评估的原始设置
  "L3 behavior|R10/R12/R15|agentic-misalignment-llms-insider-threats-2510.05179.pdf|https://arxiv.org/pdf/2510.05179"

  # L4 并行工作 + 直接反向证据：抑制情绪表达的后果
  "L4 concurrent|R2/R12/R15|gemma-needs-help-emotional-instability-mitigation-2603.10011.pdf|https://arxiv.org/pdf/2603.10011"

  # L5 补 2604.07729 自陈的两个缺口（跨模型泛化 / 线性假设）
  "L5 gap-closing|R12/R14|valence-arousal-subspace-circular-geometry-multi-behavior-2604.03147.pdf|https://arxiv.org/pdf/2604.03147"
  "L5 gap-closing|R4/R12|latent-structure-affective-representations-2604.07382.pdf|https://arxiv.org/pdf/2604.07382"
  "L5 gap-closing|R4/R-PE|why-some-emotions-harder-sae-causal-mechanisms-2604.25866.pdf|https://arxiv.org/pdf/2604.25866"
)

# 已在仓库其它批次中，本批不重复下载。
declare -a DEDUPED=(
  "L1 lineage|Zou et al. — Representation Engineering (2310.01405)|research/probe/papers/C2/representation-engineering-top-down-transparency-2310.01405.pdf"
  "L3 behavior|MacDiarmid et al. — Natural Emergent Misalignment from Reward Hacking (2511.18397)|research/probe/papers/C1/natural-emergent-misalignment-reward-hacking-2511.18397.pdf"
  "L2 decodable|Lu et al. — The Assistant Axis (2601.10387)|research/papers/assistant-axis-default-persona-stabilization-2601.10387.pdf"
  "L2 decodable|Chen/Arditi/Lindsey — Persona Vectors (2507.21509)|research/probe/papers/C2/persona-vectors-monitoring-character-traits-2507.21509.pdf"
)

mkdir -p "$PAPERS"
SUCCESS=()
FAILED=()

validate_pdf() {
  local path="$1"
  local size
  size=$(stat -f%z "$path" 2>/dev/null || stat -c%s "$path" 2>/dev/null || printf '0')
  [[ "$size" -ge 10000 ]] && file -b "$path" | grep -qi 'PDF'
}

for entry in "${ENTRIES[@]}"; do
  IFS='|' read -r strand anchor filename url <<< "$entry"
  out="$PAPERS/$filename"
  printf '==> %s [%s] %s\n' "$strand" "$anchor" "$filename"

  if [[ -f "$out" ]] && validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    cached (%s bytes)\n' "$size"
    SUCCESS+=("$strand|$anchor|$filename|$url|$size")
    continue
  fi

  curl -sLk --max-time 120 -A "$UA" -o "$out" "$url"
  if validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    ok (%s bytes)\n' "$size"
    SUCCESS+=("$strand|$anchor|$filename|$url|$size")
  else
    rm -f "$out"
    printf '    FAILED\n'
    FAILED+=("$strand|$anchor|$filename|$url")
  fi
  sleep 1
done

{
  printf '# Emotion Lineage Sweep 2026-08 — Download Summary\n\n'
  printf '> Generated by `research/download_emotion_lineage_2608.sh`\n'
  printf '> Target dir: `research/papers/emotion-lineage-2608/`\n'
  printf '> 谱系起点：`2604.07729`（分析见 `research/anthropic-emotion-concepts-2026-04/`）\n\n'
  printf '## Downloaded (%d)\n\n' "${#SUCCESS[@]}"
  printf '| Strand | VZ anchor | File | Source | Bytes |\n|---|---|---|---|---|\n'
  for row in "${SUCCESS[@]}"; do
    IFS='|' read -r strand anchor filename url size <<< "$row"
    printf '| %s | %s | `%s` | %s | %s |\n' "$strand" "$anchor" "$filename" "$url" "$size"
  done
  if (( ${#FAILED[@]} > 0 )); then
    printf '\n## Failed (%d)\n\n' "${#FAILED[@]}"
    printf '| Strand | VZ anchor | Intended file | Source |\n|---|---|---|---|\n'
    for row in "${FAILED[@]}"; do
      IFS='|' read -r strand anchor filename url <<< "$row"
      printf '| %s | %s | `%s` | %s |\n' "$strand" "$anchor" "$filename" "$url"
    done
  fi
  printf '\n## 已去重（仓库既有，不重复下载）(%d)\n\n' "${#DEDUPED[@]}"
  printf '| Strand | 论文 | 既有路径 |\n|---|---|---|\n'
  for row in "${DEDUPED[@]}"; do
    IFS='|' read -r strand item path <<< "$row"
    printf '| %s | %s | `%s` |\n' "$strand" "$item" "$path"
  done
  printf '\n> `2604.07729` 本身是 Transformer Circuits 交互版，无 PDF artifact；\n'
  printf '> 正文引用一律回 https://transformer-circuits.pub/2026/emotions/index.html。\n'
} > "$SUMMARY"

printf '\nDownloaded: %d  Failed: %d  Deduped: %d\nSummary: %s\n' \
  "${#SUCCESS[@]}" "${#FAILED[@]}" "${#DEDUPED[@]}" "$SUMMARY"
