#!/usr/bin/env bash
# Download the July 2026 personal-parametric (per-user LoRA / PEFT personalization)
# sweep — the "Mindverse / Second Me" family and its alternatives.
# Strictly deduped against research/papers/** (including continual-learning-2607).
set -uo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAPERS="$BASE/papers/personal-parametric-2607"
SUMMARY="$BASE/continual-learning-2026-07/download-summary-personal-parametric.md"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 research-survey/1.0"

declare -a ENTRIES=(
  # family|vz-anchor|filename|url
  "P0 product-lineage|R5/R6/R14|second-me-ai-native-memory-2.0-2503.08102.pdf|https://arxiv.org/pdf/2503.08102"
  "P0 product-lineage|R5/R6|memweaver-hierarchical-memory-personalized-generation-2510.07713.pdf|https://arxiv.org/pdf/2510.07713"
  "P0 product-lineage|R5/R7|prime-cognitive-dual-memory-personalized-thought-2507.04607.pdf|https://arxiv.org/pdf/2507.04607"

  "P1 one-peft-per-user|R2/R10|oppu-personalized-peft-democratizing-llm-2402.04401.pdf|https://arxiv.org/pdf/2402.04401"
  "P1 one-peft-per-user|R2/R8|per-pcs-personalized-pieces-collaborative-2406.10471.pdf|https://arxiv.org/pdf/2406.10471"
  "P1 one-peft-per-user|R5/R11|survey-personalized-llms-progress-directions-2502.11528.pdf|https://arxiv.org/pdf/2502.11528"
  "P1 one-peft-per-user|R11/R14|beyond-retrieval-compact-user-representations-2606.04547.pdf|https://arxiv.org/pdf/2606.04547"
  "P1 one-peft-per-user|R2/R10|mta-merge-then-adapt-personalized-llm-2511.20072.pdf|https://arxiv.org/pdf/2511.20072"

  "P2 hypernet-amortized|R2/R10/R15|profile-to-peft-instant-personalization-hypernetwork-2510.16282.pdf|https://arxiv.org/pdf/2510.16282"
  "P2 hypernet-amortized|R2/R10|text-to-lora-hypernetwork-adapters-2506.06105.pdf|https://arxiv.org/pdf/2506.06105"
  "P2 hypernet-amortized|R2/R10|drag-and-drop-llms-prompt-to-weights-2506.16406.pdf|https://arxiv.org/pdf/2506.16406"
  "P2 hypernet-amortized|R2/R5|generative-adapter-context-to-params-single-pass-2411.05877.pdf|https://arxiv.org/pdf/2411.05877"
  "P2 hypernet-amortized|R2/R8|amortizing-federated-adaptation-hypernetwork-lora-2606.06154.pdf|https://arxiv.org/pdf/2606.06154"

  "P3 context-to-weights|R2/R5/R13|cartridges-self-study-long-context-2506.06266.pdf|https://arxiv.org/pdf/2506.06266"
  "P3 context-to-weights|R5/R11|cartridges-keys-as-shareable-routers-2508.17032.pdf|https://arxiv.org/pdf/2508.17032"
  "P3 context-to-weights|R5/R6|context-distillation-latent-memory-management-2605.28889.pdf|https://arxiv.org/pdf/2605.28889"
  "P3 context-to-weights|R1/R6|do-lms-need-sleep-offline-recurrence-fast-weights-2605.26099.pdf|https://arxiv.org/pdf/2605.26099"

  "P4 knowledge-editing|R10/R15|wikibigedit-limits-lifelong-knowledge-editing-2503.05683.pdf|https://arxiv.org/pdf/2503.05683"
  "P4 knowledge-editing|R10/R15|lifelong-sequential-knowledge-editing-no-degradation-2502.01636.pdf|https://arxiv.org/pdf/2502.01636"
  "P4 knowledge-editing|R10/R15|labyrinth-thread-regularizations-sequential-editing-2605.26670.pdf|https://arxiv.org/pdf/2605.26670"

  "P5 serving-infra|R2/R8|s-lora-serving-thousands-concurrent-adapters-2311.03285.pdf|https://arxiv.org/pdf/2311.03285"

  "P6 federated|R8/R12|co-lora-collaborative-personalization-heterogeneous-2506.11024.pdf|https://arxiv.org/pdf/2506.11024"
)

mkdir -p "$PAPERS"
SUCCESS=()
FAILED=()

validate_pdf() {
  local path="$1"
  local size
  size=$(stat -f%z "$path" 2>/dev/null || stat -c%s "$path" 2>/dev/null || printf '0')
  [[ "$size" -ge 10000 ]] && file -b "$path" | grep -qi 'PDF'
}

for entry in "${ENTRIES[@]}"; do
  IFS='|' read -r family anchor filename url <<< "$entry"
  out="$PAPERS/$filename"
  printf '==> %s [%s] %s\n' "$family" "$anchor" "$filename"

  if [[ -f "$out" ]] && validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    cached (%s bytes)\n' "$size"
    SUCCESS+=("$family|$anchor|$filename|$url|$size")
    continue
  fi

  curl -sL --max-time 120 -A "$UA" -o "$out" "$url"
  if validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    ok (%s bytes)\n' "$size"
    SUCCESS+=("$family|$anchor|$filename|$url|$size")
  else
    rm -f "$out"
    printf '    FAILED\n'
    FAILED+=("$family|$anchor|$filename|$url")
  fi
  sleep 1
done

{
  printf '# Personal-Parametric Sweep 2026-07 — Download Summary\n\n'
  printf '> Generated by `research/download_personal_parametric_2607.sh`\n'
  printf '> Target dir: `research/papers/personal-parametric-2607/`\n\n'
  printf '## Downloaded (%d)\n\n' "${#SUCCESS[@]}"
  printf '| Family | VZ anchor | File | Source | Bytes |\n|---|---|---|---|---|\n'
  for row in "${SUCCESS[@]}"; do
    IFS='|' read -r family anchor filename url size <<< "$row"
    printf '| %s | %s | `%s` | %s | %s |\n' "$family" "$anchor" "$filename" "$url" "$size"
  done
  if (( ${#FAILED[@]} > 0 )); then
    printf '\n## Failed / link-only (%d)\n\n' "${#FAILED[@]}"
    printf '| Family | VZ anchor | Intended file | Source |\n|---|---|---|---|\n'
    for row in "${FAILED[@]}"; do
      IFS='|' read -r family anchor filename url <<< "$row"
      printf '| %s | %s | `%s` | %s |\n' "$family" "$anchor" "$filename" "$url"
    done
  fi
} > "$SUMMARY"

printf '\nDownloaded: %d  Failed: %d\nSummary: %s\n' "${#SUCCESS[@]}" "${#FAILED[@]}" "$SUMMARY"
