#!/usr/bin/env bash
# Download the Sutton "Era of Experience" / OaK line, its mechanistic
# foundations, its critiques, and the LLM camp's empirical answers.
# Mixed sources: arXiv, incompleteideas.net, DeepMind storage.
# Strictly deduped against research/papers/**.
set -uo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAPERS="$BASE/papers/sutton-experience-2607"
SUMMARY="$BASE/sutton-era-of-experience-2026-07/download-summary.md"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 research-survey/1.0"

declare -a ENTRIES=(
  # strand|vz-anchor|filename|url
  "S0 thesis|R-PE/R1/R2|era-of-experience-silver-sutton-2025.pdf|https://storage.googleapis.com/deepmind-media/Era-of-Experience%20/The%20Era%20of%20Experience%20Paper.pdf"
  "S0 thesis|R1/R3/R4|alberta-plan-for-ai-research-2208.11173.pdf|https://arxiv.org/pdf/2208.11173"
  "S0 thesis|R2/R5|big-world-hypothesis-javed-sharifnassab-sutton.pdf|http://incompleteideas.net/papers/The_Big_World_Hypothesis.pdf"
  "S0 thesis|R3/R4|sutton-talk-ttt-options-2025.pdf|http://incompleteideas.net/Talks/TTT-options-2025.pdf"
  "S0 thesis|R-PE/R9|sutton-talk-reward-hypothesis.pdf|http://incompleteideas.net/Talks/reward-hypothesis.pdf"
  "S0 thesis|R1/R2|sutton-talk-plasticity-deep-continual-learning.pdf|http://incompleteideas.net/Talks/plasticity.pdf"

  "S1 mechanism|R1/R2/R10|loss-of-plasticity-deep-continual-learning-2306.13812.pdf|https://arxiv.org/pdf/2306.13812"
  "S1 mechanism|R1/R13|streaming-deep-rl-finally-works-2410.14606.pdf|https://arxiv.org/pdf/2410.14606"
  "S1 mechanism|R3/R4/R9|reward-respecting-subtasks-model-based-rl-2202.03466.pdf|https://arxiv.org/pdf/2202.03466"
  "S1 mechanism|R2/R11|model-free-rl-scaling-unstructured-data-2311.02215.pdf|https://arxiv.org/pdf/2311.02215"

  "S2 plasticity|R1/R2|predicting-plasticity-theoretical-perspective-2605.09044.pdf|https://arxiv.org/pdf/2605.09044"
  "S2 plasticity|R1/R2|preserving-plasticity-adaptive-linearity-injection-2505.09486.pdf|https://arxiv.org/pdf/2505.09486"
  "S2 plasticity|R1/R2|self-normalized-resets-plasticity-2410.20098.pdf|https://arxiv.org/pdf/2410.20098"
  "S2 plasticity|R1/R2|activation-function-design-sustains-plasticity-2509.22562.pdf|https://arxiv.org/pdf/2509.22562"

  "S3 critique|R-PE/R12|missing-reward-active-inference-era-of-experience-2508.05619.pdf|https://arxiv.org/pdf/2508.05619"
  "S3 critique|R-PE/R12/R15|reward-hacking-era-of-large-models-2604.13602.pdf|https://arxiv.org/pdf/2604.13602"

  "S4 llm-answer|R-PE/R13|agent-learning-via-early-experience-2510.08558.pdf|https://arxiv.org/pdf/2510.08558"
  "S4 llm-answer|R13/R6|scaling-agent-learning-experience-synthesis-2511.03773.pdf|https://arxiv.org/pdf/2511.03773"
  "S4 llm-answer|R-PE/R9|reward-is-enough-llms-in-context-rl-2506.06303.pdf|https://arxiv.org/pdf/2506.06303"
  "S4 llm-answer|R6/R9|experiential-reflective-learning-self-improving-agents-2603.24639.pdf|https://arxiv.org/pdf/2603.24639"
)

# Video-only / no PDF artifact — recorded as link-only, per repo convention.
declare -a LINK_ONLY=(
  "S0 thesis|The OaK Architecture: A Vision of SuperIntelligence from Experience (RLC-2025 / AGI-2025 talk)|https://youtu.be/q9MJWfo3DCE?t=3762"
  "S0 thesis|The OaK Architecture (NeurIPS 2025 invited talk)|https://neurips.cc/virtual/2025/invited-talk/109601"
  "S0 thesis|Dertouzos Distinguished Lecture, MIT, 2026-05-13 (OaK)|https://calendar.mit.edu/event/dertouzos-distinguished-lecture-the-oak-architecture-a-vision-of-superintelligence-from-experience"
  "S3 critique|Dwarkesh Podcast interview, 2025-09-26 (LLMs are a dead end)|https://www.dwarkesh.com/p/richard-sutton"
)

mkdir -p "$PAPERS"
SUCCESS=()
FAILED=()

validate_pdf() {
  local path="$1"
  local size
  size=$(stat -f%z "$path" 2>/dev/null || stat -c%s "$path" 2>/dev/null || printf '0')
  [[ "$size" -ge 10000 ]] && file -b "$path" | grep -qi 'PDF'
}

for entry in "${ENTRIES[@]}"; do
  IFS='|' read -r strand anchor filename url <<< "$entry"
  out="$PAPERS/$filename"
  printf '==> %s [%s] %s\n' "$strand" "$anchor" "$filename"

  if [[ -f "$out" ]] && validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    cached (%s bytes)\n' "$size"
    SUCCESS+=("$strand|$anchor|$filename|$url|$size")
    continue
  fi

  curl -sLk --max-time 120 -A "$UA" -o "$out" "$url"
  if validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    ok (%s bytes)\n' "$size"
    SUCCESS+=("$strand|$anchor|$filename|$url|$size")
  else
    rm -f "$out"
    printf '    FAILED\n'
    FAILED+=("$strand|$anchor|$filename|$url")
  fi
  sleep 1
done

{
  printf '# Sutton / Era-of-Experience Sweep 2026-07 — Download Summary\n\n'
  printf '> Generated by `research/download_sutton_experience_2607.sh`\n'
  printf '> Target dir: `research/papers/sutton-experience-2607/`\n\n'
  printf '## Downloaded (%d)\n\n' "${#SUCCESS[@]}"
  printf '| Strand | VZ anchor | File | Source | Bytes |\n|---|---|---|---|---|\n'
  for row in "${SUCCESS[@]}"; do
    IFS='|' read -r strand anchor filename url size <<< "$row"
    printf '| %s | %s | `%s` | %s | %s |\n' "$strand" "$anchor" "$filename" "$url" "$size"
  done
  if (( ${#FAILED[@]} > 0 )); then
    printf '\n## Failed (%d)\n\n' "${#FAILED[@]}"
    printf '| Strand | VZ anchor | Intended file | Source |\n|---|---|---|---|\n'
    for row in "${FAILED[@]}"; do
      IFS='|' read -r strand anchor filename url <<< "$row"
      printf '| %s | %s | `%s` | %s |\n' "$strand" "$anchor" "$filename" "$url"
    done
  fi
  printf '\n## Link-only (no PDF artifact exists) (%d)\n\n' "${#LINK_ONLY[@]}"
  printf '| Strand | Item | Link |\n|---|---|---|\n'
  for row in "${LINK_ONLY[@]}"; do
    IFS='|' read -r strand item url <<< "$row"
    printf '| %s | %s | %s |\n' "$strand" "$item" "$url"
  done
  printf '\n> OaK has no paper as of 2026-07: it exists only as talks. Any OaK claim in\n'
  printf '> the analysis is sourced from the talk record, not a peer-reviewed artifact.\n'
} > "$SUMMARY"

printf '\nDownloaded: %d  Failed: %d  Link-only: %d\nSummary: %s\n' \
  "${#SUCCESS[@]}" "${#FAILED[@]}" "${#LINK_ONLY[@]}" "$SUMMARY"
