#!/usr/bin/env bash
# Download the July 2026 continual-learning landscape sweep. Every artifact is
# validated as a non-trivial PDF; incomplete or HTML responses are removed.
# Papers already present under research/papers/** are NOT re-listed here —
# this sweep is strictly the continual-learning delta.
set -uo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAPERS="$BASE/papers/continual-learning-2607"
SUMMARY="$BASE/continual-learning-2026-07/download-summary.md"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 research-survey/1.0"

declare -a ENTRIES=(
  # school|vz-anchor|filename|url
  "S0 survey|R1/R2/R13|cl-llm-methods-challenges-opportunities-2603.12658.pdf|https://arxiv.org/pdf/2603.12658"
  "S0 survey|R5/R6|agent-memory-storage-to-experience-survey-2605.06716.pdf|https://arxiv.org/pdf/2605.06716"
  "S0 survey|R2/R9/R10|agentic-ai-adaptation-posttraining-memory-skills-survey-2512.16301.pdf|https://arxiv.org/pdf/2512.16301"
  "S0 position|R5/R6/R8|position-modular-memory-key-to-cl-agents-2603.01761.pdf|https://arxiv.org/pdf/2603.01761"
  "S0 survey|R1/R2|cl-of-llms-comprehensive-survey-2404.16789.pdf|https://arxiv.org/pdf/2404.16789"
  "S0 survey|R1/R13|online-continual-learning-systematic-review-2501.04897.pdf|https://arxiv.org/pdf/2501.04897"
  "S0 bench|R12/R15|agentcl-rigorous-evaluation-cl-language-agents-2606.02461.pdf|https://arxiv.org/pdf/2606.02461"
  "S0 bench|R12/R15|continual-learning-bench-stateful-environments-2606.05661.pdf|https://arxiv.org/pdf/2606.05661"
  "S0 position|R2/R13|continual-learning-not-training-online-adaptation-agents-2511.01093.pdf|https://arxiv.org/pdf/2511.01093"

  "S1 sparse-write|R2/R10|sparse-memory-finetuning-2510.15103.pdf|https://arxiv.org/pdf/2510.15103"
  "S1 sparse-write|R2/R10|improving-sparse-memory-finetuning-2604.05248.pdf|https://arxiv.org/pdf/2604.05248"
  "S1 sparse-write|R9/R10|attribution-guided-continual-learning-llm-2605.05285.pdf|https://arxiv.org/pdf/2605.05285"

  "S2 self-edit|R9/R10/R15|seal-self-adapting-language-models-2506.10943.pdf|https://arxiv.org/pdf/2506.10943"

  "S3 mechanism|R2/R12|spurious-forgetting-continual-learning-lm-2501.13453.pdf|https://arxiv.org/pdf/2501.13453"
  "S3 mechanism|R2/R12|mechanistic-analysis-catastrophic-forgetting-2601.18699.pdf|https://arxiv.org/pdf/2601.18699"

  "S4 continual-pretrain|R2|simple-scalable-continual-pretraining-llm-2403.08763.pdf|https://arxiv.org/pdf/2403.08763"

  "S5 modular-merge|R2/R10|merge-before-forget-single-lora-continual-merging-2512.23017.pdf|https://arxiv.org/pdf/2512.23017"
  "S5 modular-merge|R2/R10|cp-moe-consistency-preserving-moe-continual-learning-2605.20247.pdf|https://arxiv.org/pdf/2605.20247"
  "S5 modular-merge|R6/R9|continual-finetuning-llm-program-memory-2605.13162.pdf|https://arxiv.org/pdf/2605.13162"

  "S6 test-time-train|R1/R3/R5|end-to-end-test-time-training-long-context-2512.23675.pdf|https://arxiv.org/pdf/2512.23675"

  "S7 agent-memory|R5/R6/R13|meta-learning-agentic-memory-designs-2602.07755.pdf|https://arxiv.org/pdf/2602.07755"
  "S7 agent-memory|R2/R7/R14|rizz-zero-interference-continual-adaptation-blackbox-agents-2606.20638.pdf|https://arxiv.org/pdf/2606.20638"
  "S7 agent-memory|R6/R10|past-is-prologue-selective-update-controller-memory-2606.31121.pdf|https://arxiv.org/pdf/2606.31121"
  "S7 agent-memory|R10/R12/R15|ssgm-governing-evolving-memory-llm-agents-2603.11768.pdf|https://arxiv.org/pdf/2603.11768"
  "S7 agent-memory|R13/R15|claas-continual-learning-as-a-service-2606.05559.pdf|https://arxiv.org/pdf/2606.05559"
)

mkdir -p "$PAPERS"
SUCCESS=()
FAILED=()

validate_pdf() {
  local path="$1"
  local size
  size=$(stat -f%z "$path" 2>/dev/null || stat -c%s "$path" 2>/dev/null || printf '0')
  [[ "$size" -ge 10000 ]] && file -b "$path" | grep -qi 'PDF'
}

for entry in "${ENTRIES[@]}"; do
  IFS='|' read -r school anchor filename url <<< "$entry"
  out="$PAPERS/$filename"
  printf '==> %s [%s] %s\n' "$school" "$anchor" "$filename"

  if [[ -f "$out" ]] && validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    cached (%s bytes)\n' "$size"
    SUCCESS+=("$school|$anchor|$filename|$url|$size")
    continue
  fi

  curl -sL --max-time 120 -A "$UA" -o "$out" "$url"
  if validate_pdf "$out"; then
    size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
    printf '    ok (%s bytes)\n' "$size"
    SUCCESS+=("$school|$anchor|$filename|$url|$size")
  else
    rm -f "$out"
    printf '    FAILED\n'
    FAILED+=("$school|$anchor|$filename|$url")
  fi
  sleep 1
done

{
  printf '# Continual-Learning Sweep 2026-07 — Download Summary\n\n'
  printf '> Generated by `research/download_continual_learning_2607.sh`\n'
  printf '> Target dir: `research/papers/continual-learning-2607/`\n\n'
  printf '## Downloaded (%d)\n\n' "${#SUCCESS[@]}"
  printf '| School | VZ anchor | File | Source | Bytes |\n|---|---|---|---|---|\n'
  for row in "${SUCCESS[@]}"; do
    IFS='|' read -r school anchor filename url size <<< "$row"
    printf '| %s | %s | `%s` | %s | %s |\n' "$school" "$anchor" "$filename" "$url" "$size"
  done
  if (( ${#FAILED[@]} > 0 )); then
    printf '\n## Failed / link-only (%d)\n\n' "${#FAILED[@]}"
    printf '| School | VZ anchor | Intended file | Source |\n|---|---|---|---|\n'
    for row in "${FAILED[@]}"; do
      IFS='|' read -r school anchor filename url <<< "$row"
      printf '| %s | %s | `%s` | %s |\n' "$school" "$anchor" "$filename" "$url"
    done
  fi
} > "$SUMMARY"

printf '\nDownloaded: %d  Failed: %d\nSummary: %s\n' "${#SUCCESS[@]}" "${#FAILED[@]}" "$SUMMARY"
