"""AutoCompany-facing Operations Brain vertical and product facade."""

from __future__ import annotations

from typing import Any

from lifeform_domain_operations.operations_brain import (
    EmptyOperationsAdviceProvider,
    OperationsAdviceProvider,
    OperationsBrainConflictError,
    OperationsBrainController,
    OperationsBrainError,
    OperationsBrainLineageError,
    OperationsBrainMemoryContractError,
    OperationsBrainReadOnlyError,
    OperationsBrainSettlementPendingError,
)
from lifeform_domain_operations.operations_brain_contracts import (
    ADVICE_SCHEMA_VERSION,
    ADVICE_V2_SCHEMA_VERSION,
    CONTEXT_PACK_SCHEMA_VERSION,
    CONTEXT_PACK_V2_SCHEMA_VERSION,
    CONTEXT_REQUEST_SCHEMA_VERSION,
    CONTEXT_REQUEST_V2_SCHEMA_VERSION,
    OUTCOME_RECEIPT_SCHEMA_VERSION,
    OUTCOME_RECEIPT_V2_SCHEMA_VERSION,
    OUTCOME_REPORT_SCHEMA_VERSION,
    OUTCOME_REPORT_V2_SCHEMA_VERSION,
    OperationsAdviceCandidate,
    OperationsAdviceKind,
    OperationsAdviceSnapshot,
    OperationsExecutionOutcome,
    OperationsConstraint,
    OperationsConstraintKind,
    OperationsContextPackSnapshot,
    OperationsContextRequest,
    OperationsCostBreakdown,
    OperationsObjectiveResult,
    OperationsDecisionKind,
    OperationsDecisionPoint,
    OperationsDependencyState,
    OperationsDivisionState,
    OperationsEstimateRange,
    OperationsEvidenceClass,
    OperationsEvidenceRef,
    OperationsEvidenceRole,
    OperationsFact,
    OperationsFactKind,
    OperationsGoalState,
    OperationsIncidentSeverity,
    OperationsIncidentState,
    OperationsMetricObservation,
    OperationsOutcomeKind,
    OperationsOutcomeReceipt,
    OperationsOutcomeReport,
    OperationsOutcomeRoute,
    OperationsOutcomeVerdict,
    OperationsPolicyAction,
    OperationsPolicyCheckpoint,
    OperationsPolicyCredit,
    OperationsPolicyDecision,
    OperationsPolicyMode,
    OperationsPolicyUpdateReceipt,
    OperationsRankedCandidate,
    OperationsRecentOutcomeState,
    OperationsRecalledExperience,
    OperationsOperatingWindow,
    OperationsReversibility,
    OperationsRiskLevel,
    OperationsSettlementState,
    OperationsStateSnapshot,
    OperationsUncertainty,
    OperationsWorkItemState,
    OperationsWorkItemStatus,
)
from lifeform_domain_operations.operations_benchmark import (
    OPERATIONS_BENCHMARK_EVALUATION_CYCLES,
    OPERATIONS_BENCHMARK_PRIMARY_METRIC,
    OPERATIONS_BENCHMARK_SEED,
    OPERATIONS_BENCHMARK_TRAINING_CYCLES,
    operations_policy_benchmark_preregistration,
    operations_policy_benchmark_scenario_set,
    run_operations_policy_benchmark,
)
from lifeform_domain_operations.operations_policy import (
    OPERATIONS_POLICY_ARTIFACT_ID,
    OPERATIONS_POLICY_NOOP_CANDIDATE_ID,
    OperationsPolicy,
    default_operations_policy_checkpoint,
    settle_operations_policy_credit,
)
from lifeform_domain_operations.operations_promotion import (
    OPERATIONS_ACTIVATION_SCOPE,
    OPERATIONS_BENCHMARK_EVIDENCE_SCOPE,
    OPERATIONS_BENCHMARK_PROTOCOL_ID,
    OPERATIONS_PROMOTION_TARGET,
    OperationsBenchmarkArmResult,
    OperationsPolicyActivationReceipt,
    OperationsPolicyBenchmarkReport,
    OperationsPromotionReview,
    issue_operations_policy_activation,
    review_operations_policy_promotion,
    validate_operations_policy_activation,
)
from lifeform_domain_operations.operations_pack import build_operations_package


def build_operations_lifeform(
    *,
    config: object | None = None,
    substrate_runtime: Any = None,
    identity_provider: Any = None,
) -> Any:
    """Build a Lifeform with reviewed Operations Brain domain priors.

    The Operations vertical adds no second cognitive owner, bespoke vitals,
    or substrate update.
    All online adaptation remains in the existing Memory, PE/credit, semantic,
    regime, and temporal owners.
    """

    from dataclasses import replace

    from lifeform_core import Lifeform, LifeformConfig

    base_config = config if isinstance(config, LifeformConfig) else LifeformConfig()
    brain_overrides: dict[str, Any] = {"rare_heavy_enabled": False}
    if substrate_runtime is not None:
        brain_overrides["substrate_mode"] = "injected"
    base_config = replace(
        base_config,
        brain_config=replace(base_config.brain_config, **brain_overrides),
    ).with_domain_experience((build_operations_package(),))
    return Lifeform(
        base_config,
        substrate_runtime=substrate_runtime,
        identity_provider=identity_provider,
    )


__all__ = (
    "ADVICE_SCHEMA_VERSION",
    "ADVICE_V2_SCHEMA_VERSION",
    "CONTEXT_PACK_SCHEMA_VERSION",
    "CONTEXT_PACK_V2_SCHEMA_VERSION",
    "CONTEXT_REQUEST_SCHEMA_VERSION",
    "CONTEXT_REQUEST_V2_SCHEMA_VERSION",
    "EmptyOperationsAdviceProvider",
    "OUTCOME_RECEIPT_SCHEMA_VERSION",
    "OUTCOME_RECEIPT_V2_SCHEMA_VERSION",
    "OUTCOME_REPORT_SCHEMA_VERSION",
    "OUTCOME_REPORT_V2_SCHEMA_VERSION",
    "OPERATIONS_POLICY_ARTIFACT_ID",
    "OPERATIONS_ACTIVATION_SCOPE",
    "OPERATIONS_BENCHMARK_EVALUATION_CYCLES",
    "OPERATIONS_BENCHMARK_EVIDENCE_SCOPE",
    "OPERATIONS_BENCHMARK_PRIMARY_METRIC",
    "OPERATIONS_BENCHMARK_PROTOCOL_ID",
    "OPERATIONS_BENCHMARK_SEED",
    "OPERATIONS_BENCHMARK_TRAINING_CYCLES",
    "OPERATIONS_POLICY_NOOP_CANDIDATE_ID",
    "OPERATIONS_PROMOTION_TARGET",
    "OperationsAdviceCandidate",
    "OperationsAdviceKind",
    "OperationsAdviceProvider",
    "OperationsAdviceSnapshot",
    "OperationsBrainConflictError",
    "OperationsBrainController",
    "OperationsBrainError",
    "OperationsBrainLineageError",
    "OperationsBrainMemoryContractError",
    "OperationsBrainReadOnlyError",
    "OperationsBrainSettlementPendingError",
    "OperationsBenchmarkArmResult",
    "OperationsExecutionOutcome",
    "OperationsConstraint",
    "OperationsConstraintKind",
    "OperationsContextPackSnapshot",
    "OperationsContextRequest",
    "OperationsCostBreakdown",
    "OperationsObjectiveResult",
    "OperationsDecisionKind",
    "OperationsDecisionPoint",
    "OperationsDependencyState",
    "OperationsDivisionState",
    "OperationsEstimateRange",
    "OperationsEvidenceClass",
    "OperationsEvidenceRef",
    "OperationsEvidenceRole",
    "OperationsFact",
    "OperationsFactKind",
    "OperationsGoalState",
    "OperationsIncidentSeverity",
    "OperationsIncidentState",
    "OperationsMetricObservation",
    "OperationsOutcomeKind",
    "OperationsOutcomeReceipt",
    "OperationsOutcomeReport",
    "OperationsOutcomeRoute",
    "OperationsOutcomeVerdict",
    "OperationsPolicy",
    "OperationsPolicyAction",
    "OperationsPolicyActivationReceipt",
    "OperationsPolicyBenchmarkReport",
    "OperationsPolicyCheckpoint",
    "OperationsPolicyCredit",
    "OperationsPolicyDecision",
    "OperationsPolicyMode",
    "OperationsPolicyUpdateReceipt",
    "OperationsRankedCandidate",
    "OperationsPromotionReview",
    "OperationsRecentOutcomeState",
    "OperationsRecalledExperience",
    "OperationsOperatingWindow",
    "OperationsReversibility",
    "OperationsRiskLevel",
    "OperationsSettlementState",
    "OperationsStateSnapshot",
    "OperationsUncertainty",
    "OperationsWorkItemState",
    "OperationsWorkItemStatus",
    "build_operations_lifeform",
    "build_operations_package",
    "default_operations_policy_checkpoint",
    "issue_operations_policy_activation",
    "operations_policy_benchmark_preregistration",
    "operations_policy_benchmark_scenario_set",
    "review_operations_policy_promotion",
    "run_operations_policy_benchmark",
    "settle_operations_policy_credit",
    "validate_operations_policy_activation",
)
