"""Unified proprietary synthetic experience corpus toolkit."""

from .canonical import (
    canonical_json,
    manifest_from_json,
    stable_hash,
    trajectory_from_json,
)
from .contracts import (
    SCHEMA_VERSION,
    AdjudicationStatus,
    AnnotationRecord,
    AnnotationSource,
    ArtifactRef,
    CorpusManifest,
    CorpusSplit,
    CountEntry,
    ExperienceSession,
    ExperienceTrajectory,
    ExperienceTurn,
    GenerationTier,
    KeyValue,
    LatentTruthFrame,
    ProvenanceRecord,
    QualityRecord,
    QualitySeverity,
    ScenarioBlueprint,
    SnapshotFrame,
    Timescale,
    Track,
    TrainingUse,
    TurnRole,
)

__version__ = "0.1.0"

__all__ = [
    "SCHEMA_VERSION",
    "AdjudicationStatus",
    "AnnotationRecord",
    "AnnotationSource",
    "ArtifactRef",
    "CorpusManifest",
    "CorpusSplit",
    "CountEntry",
    "ExperienceSession",
    "ExperienceTrajectory",
    "ExperienceTurn",
    "GenerationTier",
    "KeyValue",
    "LatentTruthFrame",
    "ProvenanceRecord",
    "QualityRecord",
    "QualitySeverity",
    "ScenarioBlueprint",
    "SnapshotFrame",
    "Timescale",
    "Track",
    "TrainingUse",
    "TurnRole",
    "__version__",
    "canonical_json",
    "manifest_from_json",
    "stable_hash",
    "trajectory_from_json",
]
