"""Plain-text OpenAI-compat client used by the user simulator.

The companion-bench user simulator (``companion_bench.user_simulator``)
expects an :class:`UtteranceClient` Protocol whose ``complete()`` method
returns a *string* — a single natural-language utterance generated by an
LLM. The simulator does not want JSON-mode output.

``lifeform_core.OpenAiCompatJsonClient`` is JSON-mode-only by contract
(it forces ``response_format={"type": "json_object"}``), so we cannot
reuse it directly. This module ships a sibling client that:

* takes the same :class:`OpenAiCompatConfig` (so secrets / base_url /
  model are sourced through the **same** deployment-layer plumbing as
  protocol uptake — single point of provenance);
* posts ``POST {base_url}/chat/completions`` without ``response_format``;
* honours ``temperature`` + ``seed`` parameters passed per call so the
  simulator can request deterministic generation (RFC §3 P3
  reproducibility guarantees);
* fails loudly on every error path (no swallowed exceptions, no
  ``hasattr`` defensive guards — per ``no-swallow-errors-no-hasattr-
  abuse.mdc``).

Why this lives in ``lifeform-service`` and not ``lifeform-core``
================================================================

The base ``OpenAiCompatJsonClient`` is JSON-mode and serves the
protocol-uptake / reflection / batch-extraction paths that ALL
``lifeform-*`` wheels can reuse. The plain-text variant is currently
only needed by the governance-demo simulator surface mounted by
``lifeform-service``, so we keep it next to the deployment-layer
``build_client_from_env`` helper that constructs it.

If a second consumer ever needs plain-text completion, this class
should be lifted into ``lifeform-core`` alongside its JSON sibling.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any

from lifeform_core import OpenAiCompatConfig

from lifeform_service.openai_compat_client import PROVIDER_PRESETS


class OpenAiUtteranceClient:
    """OpenAI-compat chat-completions client returning plain text.

    Satisfies ``companion_bench.user_simulator.UtteranceClient`` via
    duck-typed ``complete()``. We do not subclass the Protocol explicitly
    because Protocol subclassing would pull a runtime ``companion_bench``
    import into ``lifeform-service``'s public surface; the duck-type is
    sufficient and keeps the import cost in the route handler.
    """

    def __init__(self, config: OpenAiCompatConfig) -> None:
        if not config.base_url.strip():
            raise ValueError(
                "OpenAiUtteranceClient: base_url must be non-empty"
            )
        if not config.api_key.strip():
            raise ValueError(
                "OpenAiUtteranceClient: api_key must be non-empty"
            )
        if not config.model.strip():
            raise ValueError(
                "OpenAiUtteranceClient: model must be non-empty"
            )
        self._config = config

    @property
    def model(self) -> str:
        return self._config.model

    @property
    def base_url(self) -> str:
        return self._config.base_url

    def complete(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        seed: int,
    ) -> str:
        payload: dict[str, Any] = {
            "model": self._config.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": float(temperature),
            "seed": int(seed),
            # Cap the user-utterance length aggressively; the prompt
            # itself asks for 1-3 sentences, so 256 completion tokens is
            # already generous. This protects against a runaway model
            # filling the simulator history with paragraphs.
            "max_tokens": 256,
        }
        body = json.dumps(payload).encode("utf-8")
        url = self._config.base_url.rstrip("/") + "/chat/completions"
        request = urllib.request.Request(
            url,
            data=body,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self._config.api_key}",
            },
        )
        try:
            with urllib.request.urlopen(
                request, timeout=self._config.timeout_seconds
            ) as response:
                response_body = response.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"utterance LLM call failed with HTTP "
                f"{exc.code} {exc.reason}: {error_body[:500]}"
            ) from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(
                f"utterance LLM call failed: {exc.reason}"
            ) from exc

        try:
            envelope = json.loads(response_body)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                f"utterance LLM returned non-JSON envelope: "
                f"{response_body[:500]}"
            ) from exc

        choices = envelope.get("choices") or []
        if not choices:
            raise RuntimeError(
                "utterance LLM response missing 'choices'"
            )
        message = choices[0].get("message") or {}
        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            raise RuntimeError(
                "utterance LLM response missing 'content' string"
            )
        return content.strip()


def _env(name: str, default: str = "") -> str:
    return (os.environ.get(name) or default).strip()


def build_utterance_client_from_env() -> OpenAiUtteranceClient | None:
    """Construct an :class:`OpenAiUtteranceClient` from env, or ``None``.

    Reuses the same provider preset table used by
    :func:`lifeform_service.openai_compat_client.build_client_from_env`
    (openrouter / openai / qwen / dashscope / vllm / lifeform-openai-compat), so the
    operator only sets ``PROTOCOL_LLM_API_KEY`` (+ optional
    ``PROTOCOL_LLM_PROVIDER``) and both the JSON-mode and the
    plain-text clients pick up the same credentials.

    Returns:
        Configured client, or ``None`` if no API key is present. Callers
        branch on ``None`` to fall back to a deterministic fake
        utterance backend.

    Raises:
        ValueError: when provider has no preset and
            ``PROTOCOL_LLM_BASE_URL`` is not set, or when the resulting
            model is empty. Mirrors :func:`build_client_from_env` for
            consistency — we want fail-loud on broken provider config,
            not a silent fallback to the fake backend.
    """

    api_key = _env("PROTOCOL_LLM_API_KEY")
    if not api_key:
        return None

    # Default provider must match the JSON-mode client
    # (lifeform_service.openai_compat_client).
    provider = _env("PROTOCOL_LLM_PROVIDER", "openrouter").lower()
    preset = PROVIDER_PRESETS.get(provider)

    base_url = _env("PROTOCOL_LLM_BASE_URL")
    if not base_url:
        if preset is None:
            raise ValueError(
                f"PROTOCOL_LLM_PROVIDER={provider!r} is not a known "
                f"preset; set PROTOCOL_LLM_BASE_URL explicitly. "
                f"Known providers: {sorted(PROVIDER_PRESETS)}"
            )
        base_url = preset.base_url

    model = _env("PROTOCOL_LLM_MODEL")
    if not model:
        model = preset.default_model if preset is not None else ""
        if not model:
            raise ValueError(
                "PROTOCOL_LLM_MODEL must be set when no preset "
                "supplies a default."
            )

    timeout_raw = _env("PROTOCOL_LLM_TIMEOUT_SECONDS")
    try:
        timeout = float(timeout_raw) if timeout_raw else 60.0
    except ValueError:
        timeout = 60.0

    return OpenAiUtteranceClient(
        OpenAiCompatConfig(
            base_url=base_url,
            api_key=api_key,
            model=model,
            timeout_seconds=timeout,
        )
    )


__all__ = [
    "OpenAiUtteranceClient",
    "build_utterance_client_from_env",
]
