"""Volvence Forge: isolated, evidence-driven RSI tooling."""

from .config import ForgeConfig, ForgePaths
from .mine import FailureAnalysis, mine_bundle, mine_failures, write_failure_patterns
from .research_control import (
    CommandExecution,
    PraxistCommandRunner,
    ResearchApprovalResult,
    ResearchControlError,
    ResearchControlStatus,
    ResearchRequestResult,
    SubprocessPraxistRunner,
    inspect_research_request,
    list_research_inbox,
    reconcile_research_control,
    review_research_request,
    submit_research_request,
    validate_research_request,
)
from .research_discovery import (
    CodexNativeResearchDiscoveryBackend,
    ReplayResearchDiscoveryBackend,
    ResearchBoundRequestResult,
    ResearchDemandSealResult,
    discover_research_topics,
    review_research_topic,
    seal_research_demand,
    submit_bound_topic_for_a0,
    validate_research_demand,
    validate_research_demand_binding,
    validate_research_discovery_run,
    validate_research_topic_proposal,
)
from .research_loop import (
    ResearchLoopError,
    ResearchLoopResult,
    run_demand_research_loop_once,
)
from .research_opportunity import (
    ResearchOpportunityError,
    ResearchOpportunityStatus,
    ResearchScanResult,
    scan_research_opportunities,
    validate_research_opportunity,
)
from .research_portfolio import (
    ResearchPortfolioError,
    ResearchPortfolioSealResult,
    inspect_research_portfolio,
    run_research_portfolio_once,
    seal_research_portfolio,
    validate_research_portfolio,
)
from .research_promotion import (
    CandidateImportResult,
    PromotionReceiptResult,
    ResearchPipelineError,
    authorize_research_candidate,
    import_praxist_candidate,
    rollback_research_candidate,
    validate_research_candidate,
    validate_research_task,
)
from .sources import SourceBundle, load_source_bundle, source_bundle_digest

__all__ = [
    "FailureAnalysis",
    "ForgeConfig",
    "ForgePaths",
    "CommandExecution",
    "CodexNativeResearchDiscoveryBackend",
    "CandidateImportResult",
    "PraxistCommandRunner",
    "PromotionReceiptResult",
    "ResearchApprovalResult",
    "ResearchBoundRequestResult",
    "ResearchDemandSealResult",
    "ResearchControlError",
    "ResearchControlStatus",
    "ResearchOpportunityError",
    "ResearchOpportunityStatus",
    "ResearchPortfolioError",
    "ResearchPortfolioSealResult",
    "ResearchPipelineError",
    "ResearchRequestResult",
    "ResearchLoopError",
    "ResearchLoopResult",
    "ResearchScanResult",
    "ReplayResearchDiscoveryBackend",
    "SourceBundle",
    "SubprocessPraxistRunner",
    "load_source_bundle",
    "discover_research_topics",
    "authorize_research_candidate",
    "inspect_research_request",
    "inspect_research_portfolio",
    "import_praxist_candidate",
    "list_research_inbox",
    "mine_bundle",
    "mine_failures",
    "reconcile_research_control",
    "review_research_request",
    "review_research_topic",
    "run_demand_research_loop_once",
    "run_research_portfolio_once",
    "seal_research_demand",
    "seal_research_portfolio",
    "scan_research_opportunities",
    "source_bundle_digest",
    "rollback_research_candidate",
    "submit_research_request",
    "submit_bound_topic_for_a0",
    "validate_research_candidate",
    "validate_research_opportunity",
    "validate_research_portfolio",
    "validate_research_request",
    "validate_research_demand",
    "validate_research_demand_binding",
    "validate_research_discovery_run",
    "validate_research_topic_proposal",
    "validate_research_task",
    "write_failure_patterns",
]

__version__ = "0.1.0"
