"""Build Phase D decision report from Phase 2/3 multi-seed evidence."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


_DECISION_SCHEMA_VERSION = "phase2-shadow-decision-report.v1"


def _decision_for(*, runner_kind: str, winrate: float) -> tuple[str, tuple[str, ...]]:
    if runner_kind == "synthetic":
        return (
            "REMAIN_SHADOW",
            ("synthetic evidence validates wiring/schema only; real evidence required",),
        )
    if winrate >= 0.6:
        return ("ACTIVE_CANDIDATE", (f"head-to-head winrate {winrate:.4f} >= 0.6000",))
    if winrate >= 0.5:
        return ("REMAIN_SHADOW", (f"head-to-head winrate {winrate:.4f} is non-negative but below ACTIVE threshold",))
    return ("DISABLED", (f"head-to-head winrate {winrate:.4f} < 0.5000",))


def build_decision_report(payload: dict[str, Any]) -> dict[str, Any]:
    if payload["schema_version"] != "phase2-shadow-evidence-multiseed.v1":
        raise ValueError(
            f"unsupported input schema_version {payload['schema_version']!r}"
        )
    runner_kind = payload["runner_kind"]
    decisions: list[dict[str, Any]] = []
    for row in payload["head_to_head_results"]:
        winrate = float(row["winrate_a_vs_b"])
        decision, reasons = _decision_for(runner_kind=runner_kind, winrate=winrate)
        decisions.append(
            {
                "profile_label": row["profile_a"],
                "baseline_label": row["profile_b"],
                "decision": decision,
                "head_to_head_winrate": winrate,
                "reasons": list(reasons),
            }
        )
    return {
        "schema_version": _DECISION_SCHEMA_VERSION,
        "artifact_kind": "phase2_shadow_decision_report",
        "source_schema_version": payload["schema_version"],
        "runner_kind": runner_kind,
        "include_phase3_combos": payload["include_phase3_combos"],
        "decisions": decisions,
        "provenance": payload["provenance"],
    }


def _build_markdown(report: dict[str, Any], *, source_path: Path) -> str:
    rows = "\n".join(
        f"| `{item['profile_label']}` | `{item['decision']}` | {item['head_to_head_winrate']:.4f} | {'; '.join(item['reasons'])} |"
        for item in report["decisions"]
    )
    if not rows:
        rows = "| _(none)_ |  |  |  |"
    return f"""# Phase 2/3 Shadow Decision Report

> Generated by `scripts/build_phase2_shadow_decision_report.py`.

- Source: `{source_path}`
- Runner kind: `{report['runner_kind']}`
- Includes Phase 3 combos: `{report['include_phase3_combos']}`

| Profile | Decision | Head-to-head winrate | Reasons |
|---|---|---:|---|
{rows}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_json", type=Path)
    parser.add_argument("--output-dir", type=Path, default=None)
    args = parser.parse_args()

    input_payload = json.loads(args.input_json.read_text(encoding="utf-8"))
    report = build_decision_report(input_payload)
    output_dir = args.output_dir or args.input_json.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "phase2_shadow_decision_report.json"
    md_path = output_dir / "phase2_shadow_decision_report.md"
    json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(_build_markdown(report, source_path=args.input_json), encoding="utf-8")
    print(f"wrote {json_path}")
    print(f"wrote {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
