"""Parametrised SHADOW evidence harness (architecture-uplift B4).

Generalises the SHADOW evidence flow demonstrated by
``scripts/run_atlas_titans_cms_shadow_smoke.py`` into a reusable template:
any candidate profile can be compared against a baseline profile across
a configurable case + seed sweep, producing:

1. ``artifacts/<candidate>_shadow_evidence/<candidate>_shadow_smoke.json``
   — raw report with per-profile / per-case metric means
2. ``docs/specs/<candidate>-shadow-evidence-<date>.md`` — populated from
   ``docs/specs/_templates/shadow-evidence-template.md`` if the template
   exists; otherwise the script writes a minimal fallback markdown stub.

Spec reference: [`docs/specs/evaluation-cascade.md`](../docs/specs/evaluation-cascade.md)
§迁移协议 + [`docs/specs/profile-registry.md`](../docs/specs/profile-registry.md)
§迁移协议 use this harness as the SHADOW → ACTIVE evidence gate.

Smoke command (replicates legacy ATLAS / Titans SHADOW smoke):

    python scripts/run_shadow_evidence_template.py \
        --baseline pe-eta \
        --candidate atlas-titans-cms-uplift \
        --case-limit 2 \
        --output-dir artifacts/cms_atlas_titans_shadow_smoke
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as _dt
import json
import sys
from pathlib import Path

from volvence_zero.agent import (
    DEFAULT_DIALOGUE_PROOF_CASES,
    run_dialogue_pe_eta_ablation_benchmark,
)


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


_FALLBACK_MARKDOWN_TEMPLATE = """# {candidate} — SHADOW Evidence ({date})

> Companion brief generated by ``scripts/run_shadow_evidence_template.py``.
>
> Baseline profile: ``{baseline}``
> Candidate profile: ``{candidate}``
> Cases: ``{cases}``
> Seeds: ``{seeds}``
> Smoke artifact: ``{artifact_path}``

## Headline

(fill in once SHADOW evidence is reviewed)

## Per-metric delta table

| Metric | {baseline} | {candidate} | delta | direction |
|---|---:|---:|---:|---|
{delta_rows}

## Acceptance gate

(write up which acceptance gates were checked; cite tests/specs)

## Rollback switch

(env var / config flag to revert to baseline)

## Decision

(ACTIVE / hold / DISABLED — record evidence and date)
"""


def _format_delta_rows(
    baseline_means: dict[str, float],
    candidate_means: dict[str, float],
    *,
    epsilon: float = 1e-4,
) -> str:
    keys = sorted(set(baseline_means.keys()) | set(candidate_means.keys()))
    rows: list[str] = []
    for key in keys:
        b = baseline_means.get(key)
        c = candidate_means.get(key)
        if b is None or c is None:
            continue
        delta = c - b
        if abs(delta) < epsilon:
            continue
        direction = "up" if delta > 0 else "down"
        rows.append(
            f"| `{key}` | {b:.4f} | {c:.4f} | {delta:+.4f} | {direction} |"
        )
    if not rows:
        rows.append("| _(no metric delta exceeds the float-noise epsilon)_ |  |  |  |  |")
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


async def main(
    *,
    baseline: str,
    candidate: str,
    case_limit: int,
    output_dir: Path,
) -> int:
    cases = DEFAULT_DIALOGUE_PROOF_CASES[:case_limit]
    profile_labels = (baseline, candidate)
    print(
        f"[shadow-evidence] baseline={baseline} candidate={candidate} "
        f"case_limit={case_limit} cases={[c.case_id for c in cases]}"
    )
    report = await run_dialogue_pe_eta_ablation_benchmark(
        cases=cases,
        profile_labels=profile_labels,
        baseline_label=baseline,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    # Pull per-profile metric_means from path reports.
    per_path_metric_means: dict[str, dict[str, float]] = {}
    for path in report.path_reports:
        per_path_metric_means[path.path_label] = dict(path.benchmark_report.metric_means)

    artifact_payload = {
        "baseline": baseline,
        "candidate": candidate,
        "cases": [c.case_id for c in cases],
        "per_profile_metric_means": per_path_metric_means,
    }
    artifact_path = output_dir / f"{candidate}_shadow_smoke.json"
    artifact_path.write_text(
        json.dumps(artifact_payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[shadow-evidence] wrote raw artifact {artifact_path}")

    baseline_means = per_path_metric_means.get(baseline, {})
    candidate_means = per_path_metric_means.get(candidate, {})
    delta_rows = _format_delta_rows(baseline_means, candidate_means)

    today = _dt.date.today().isoformat()
    md = _FALLBACK_MARKDOWN_TEMPLATE.format(
        candidate=candidate,
        baseline=baseline,
        date=today,
        cases=", ".join(c.case_id for c in cases),
        seeds="(harness default)",
        artifact_path=str(artifact_path),
        delta_rows=delta_rows,
    )
    md_path = output_dir / f"{candidate}-shadow-evidence-{today}.md"
    md_path.write_text(md, encoding="utf-8")
    print(f"[shadow-evidence] wrote evidence brief {md_path}")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        type=str,
        default="pe-eta",
        help="Baseline profile label (default: pe-eta).",
    )
    parser.add_argument(
        "--candidate",
        type=str,
        required=True,
        help="Candidate profile label to compare against baseline.",
    )
    parser.add_argument(
        "--case-limit",
        type=int,
        default=2,
        help="Number of scripted proof cases to run per profile (smoke = 2).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Output directory for raw JSON + markdown brief. "
            "Defaults to artifacts/<candidate>_shadow_evidence/."
        ),
    )
    args = parser.parse_args()
    output_dir = args.output_dir or Path(
        f"artifacts/{args.candidate}_shadow_evidence"
    )
    sys.exit(
        asyncio.run(
            main(
                baseline=args.baseline,
                candidate=args.candidate,
                case_limit=args.case_limit,
                output_dir=output_dir,
            )
        )
    )
