"""Semantic state package facade.

Re-exports the nine semantic-state owners and their contract surface.
External consumers keep using ``from volvence_zero.semantic_state import X``
and are unaffected by the Slice S.1 file split.

Capability-domain files:

* :mod:`.contracts` — enums, dataclasses, snapshot types, readout helpers
* :mod:`.lifecycle` — operation-to-lifecycle dispatch + outcome records
* :mod:`.proposal_runtime` — ABC, four event adapters, event builders
* :mod:`.store` — single-writer :class:`SemanticStateStore` + clone
* :mod:`.owners` — nine :class:`RuntimeModule` owners + factory
"""

from __future__ import annotations

from volvence_zero.semantic_state.contracts import (
    ALLOWED_FUNNEL_STAGES,
    FUNNEL_STAGE_CONVERTING,
    FUNNEL_STAGE_DISCOVERY,
    FUNNEL_STAGE_NURTURING,
    FUNNEL_STAGE_PROSPECTING,
    FUNNEL_STAGE_RECOMMENDING,
    FUNNEL_STAGE_REPURCHASING,
    FUNNEL_STAGE_UNKNOWN,
    SEMANTIC_OWNER_SLOTS,
    SELF_SEMANTIC_OWNER_SLOTS,
    WORLD_SEMANTIC_OWNER_SLOTS,
    AdvocacyState,
    AlignmentState,
    BeliefAssumptionSnapshot,
    BoundaryConsentSnapshot,
    CommitmentLifecycleEntry,
    CommitmentOutcomeKind,
    CommitmentSnapshot,
    ExecutionResultLifecycleEntry,
    ExecutionResultOutcome,
    ExecutionResultSnapshot,
    ExternalSemanticEvent,
    ExternalSemanticEventBatch,
    FollowupPolicy,
    GoalValueSnapshot,
    OpenLoopSnapshot,
    PlanIntentLifecycleEntry,
    PlanIntentOutcome,
    PlanIntentSnapshot,
    ProfileSemanticEvent,
    RelationshipStateSnapshot,
    ReviewedKnowledgeSemanticEvent,
    SemanticProposal,
    SemanticProposalBatch,
    SemanticProposalOperation,
    SemanticRecord,
    SemanticSnapshotValue,
    TaskSemanticEvent,
    ToolResultSemanticEvent,
    UserModelSnapshot,
    load_semantic_json_schema,
    load_semantic_prompt_template,
    semantic_control_signal,
    semantic_snapshot_description,
)
from volvence_zero.semantic_state.lifecycle import (
    commitment_followup_policy_for_operation,
    commitment_lifecycle_for_operation,
    commitment_outcome_for_operation,
    execution_result_outcome_for_operation,
    plan_intent_outcome_for_operation,
)
from volvence_zero.semantic_state.proposal_runtime import (
    AdapterSemanticProposalRuntime,
    NoOpSemanticProposalRuntime,
    ProfileSemanticAdapter,
    ReviewedKnowledgeSemanticAdapter,
    SemanticEventAdapter,
    SemanticProposalRuntime,
    TaskEventSemanticAdapter,
    ToolResultSemanticAdapter,
    semantic_events_from_profile,
    semantic_events_from_reviewed_knowledge,
    semantic_events_from_task_event,
    semantic_events_from_tool_result,
)
from volvence_zero.semantic_state.store import (
    SemanticStateStore,
    clone_semantic_store,
)
from volvence_zero.semantic_state.owners import (
    SEMANTIC_MODULE_TYPES,
    BeliefAssumptionModule,
    BoundaryConsentModule,
    CommitmentModule,
    ExecutionResultModule,
    GoalValueModule,
    OpenLoopModule,
    PlanIntentModule,
    RelationshipStateModule,
    SemanticOwnerModule,
    UserModelModule,
    apply_semantic_writeback_result,
    build_semantic_modules,
    semantic_snapshot_counts,
)

__all__ = [
    "ALLOWED_FUNNEL_STAGES",
    "AdapterSemanticProposalRuntime",
    "AdvocacyState",
    "AlignmentState",
    "BeliefAssumptionModule",
    "BeliefAssumptionSnapshot",
    "BoundaryConsentModule",
    "BoundaryConsentSnapshot",
    "FUNNEL_STAGE_CONVERTING",
    "FUNNEL_STAGE_DISCOVERY",
    "FUNNEL_STAGE_NURTURING",
    "FUNNEL_STAGE_PROSPECTING",
    "FUNNEL_STAGE_RECOMMENDING",
    "FUNNEL_STAGE_REPURCHASING",
    "FUNNEL_STAGE_UNKNOWN",
    "CommitmentLifecycleEntry",
    "CommitmentModule",
    "CommitmentOutcomeKind",
    "CommitmentSnapshot",
    "ExecutionResultLifecycleEntry",
    "ExecutionResultModule",
    "ExecutionResultOutcome",
    "ExecutionResultSnapshot",
    "ExternalSemanticEvent",
    "ExternalSemanticEventBatch",
    "FollowupPolicy",
    "GoalValueModule",
    "GoalValueSnapshot",
    "NoOpSemanticProposalRuntime",
    "OpenLoopModule",
    "OpenLoopSnapshot",
    "PlanIntentLifecycleEntry",
    "PlanIntentModule",
    "PlanIntentOutcome",
    "PlanIntentSnapshot",
    "ProfileSemanticAdapter",
    "ProfileSemanticEvent",
    "RelationshipStateModule",
    "RelationshipStateSnapshot",
    "ReviewedKnowledgeSemanticAdapter",
    "ReviewedKnowledgeSemanticEvent",
    "SEMANTIC_MODULE_TYPES",
    "SEMANTIC_OWNER_SLOTS",
    "SELF_SEMANTIC_OWNER_SLOTS",
    "WORLD_SEMANTIC_OWNER_SLOTS",
    "SemanticEventAdapter",
    "SemanticOwnerModule",
    "SemanticProposal",
    "SemanticProposalBatch",
    "SemanticProposalOperation",
    "SemanticProposalRuntime",
    "SemanticRecord",
    "SemanticSnapshotValue",
    "SemanticStateStore",
    "TaskEventSemanticAdapter",
    "TaskSemanticEvent",
    "ToolResultSemanticAdapter",
    "ToolResultSemanticEvent",
    "UserModelModule",
    "UserModelSnapshot",
    "apply_semantic_writeback_result",
    "build_semantic_modules",
    "clone_semantic_store",
    "commitment_followup_policy_for_operation",
    "commitment_lifecycle_for_operation",
    "commitment_outcome_for_operation",
    "execution_result_outcome_for_operation",
    "load_semantic_json_schema",
    "load_semantic_prompt_template",
    "plan_intent_outcome_for_operation",
    "semantic_control_signal",
    "semantic_events_from_profile",
    "semantic_events_from_reviewed_knowledge",
    "semantic_events_from_task_event",
    "semantic_events_from_tool_result",
    "semantic_snapshot_counts",
    "semantic_snapshot_description",
]
