"""DLaaS platform-tier typed dataclass surface.

Stable wire-format types shared across `dlaas-platform-*` wheels. This
package is the foundation of the platform tier: zero `vz-*` (besides
the typed taxonomy in ``vz-contracts``) and zero `lifeform-*` imports.

Public exports:

* Runtime envelope (Slice 1): :class:`InteractionEnvelope`,
  :class:`InteractionType`, :class:`InteractionMode`,
  :class:`OutputAct`, :class:`FeedbackPayload`,
  :class:`OutputContract`.
* Dispatch vocabulary (Slice 2): :class:`FeedbackValence`,
  :class:`ObservationType`, :class:`CommandName` +
  :func:`feedback_valence_to_outcome_kind`.
* Control-plane resources (Slice 3 / 4): :class:`TenantSpec`,
  :class:`ShellSpec` / :class:`ShellKind`, :class:`AssetSpec`,
  :class:`TemplateSpec` / :class:`TemplateStatus` /
  :class:`TemplateActivationStatus` /
  :class:`TemplateVersionSpec` /
  :class:`TemplateAssetLinkSpec` /
  :class:`ReadinessReport`,
  :class:`ContractSpec` / :class:`ContractStatus`,
  :class:`FocusPersonSpec`, :class:`IdentityLinkSpec`,
  :class:`HandoffTicketSpec` / :class:`HandoffStatus`.
"""

from __future__ import annotations

from dlaas_platform_contracts.adoption import (
    AdoptionConfig,
    MemoryPolicySelection,
    OpsPolicySelection,
    ProtocolSelection,
    SubstrateSelection,
    ToolPolicySelection,
    TrainingPolicySelection,
    VerticalSelection,
)
from dlaas_platform_contracts.applications import (
    ApplicationApprovalSpec,
    ApplicationSpec,
)
from dlaas_platform_contracts.bake import (
    ANGLE_STAGE_ORDER,
    BakeAngle,
    BakeAngleJob,
    BakeAngleKind,
    BakeAngleResult,
    BakeAngleStatus,
    BakeContractError,
    BakeRequest,
    BakeRun,
    BakeRunEvent,
    BakeRunStatus,
    RawMaterial,
    VALID_CORPUS_MODES,
    VALID_RAW_MATERIAL_KINDS,
    angle_stage_index,
    is_terminal_angle_status,
    is_terminal_run_status,
    rollup_run_status,
)
from dlaas_platform_contracts.dispatch_vocab import (
    CommandName,
    FeedbackValence,
    ObservationType,
    feedback_valence_to_outcome_kind,
    is_experience_observation,
)
from dlaas_platform_contracts.experience import (
    CAPABILITY_EXPERIENCE_BINDING,
    EXPERIENCE_BRIEF_SCHEMA_VERSION,
    EXPERIENCE_RECEIPT_SCHEMA_VERSION,
    EXPERIENCE_REFLECTION_SCHEMA_VERSION,
    ExperienceBriefSpec,
    ExperienceBudgetHint,
    ExperienceDomainBinding,
    ExperienceReceiptSpec,
    ExperienceReflectionSpec,
    MARKETING_EXPERIENCE_BINDING,
    MEMORIAL_EXPERIENCE_BINDING,
    READER_DIALOGUE_EXPERIENCE_BINDING,
    builtin_experience_domain_bindings,
    find_binding_for_brief_kind,
)
from dlaas_platform_contracts.debug import (
    DebugAnalysisReport,
    DebugAnalysisRequest,
    DebugAppRegistration,
    DebugEventEnvelope,
    DebugFieldDefinition,
    DebugFieldOwner,
    DebugFieldType,
    DebugPrivacyLevel,
    DebugSchema,
    DebugVersionSuggestion,
)
from dlaas_platform_contracts.envelope import (
    DEFAULT_PROTOCOL_VERSION,
    FeedbackPayload,
    InteractionEnvelope,
    InteractionMode,
    InteractionType,
    OutputAct,
    OutputContract,
)
from dlaas_platform_contracts.eval import (
    AudienceProfileSpec,
    ExamQuestionSpec,
    ExamRunSpec,
    ExamRunStatus,
    ExamSubmissionScore,
    LaunchLicenseSpec,
    RubricEntry,
)
from dlaas_platform_contracts.interview import (
    InterviewRunSpec,
    InterviewRunStatus,
    InterviewTurn,
    InterviewerKind,
)
from dlaas_platform_contracts.lifecycle import (
    InstanceLifecycleState,
    InstanceStatus,
    SleepRequest,
    WakeRequest,
)
from dlaas_platform_contracts.intake import (
    AssetIntakeDecision,
    AssetIntakeIntent,
    AssetIntakeRequest,
    AssetMediaKind,
)
from dlaas_platform_contracts.governance import (
    ArtifactKind,
    ArtifactRecord,
    AuditEvent,
    BillingEvent,
    ConsentRecord,
    DataExportJob,
    DataJobStatus,
    DeletionJob,
    EvalGateDecision,
    EvalRun,
    EvalRunStatus,
    EventStreamRecord,
    EvidenceTrace,
    PolicySnapshot,
    PromotionDecision,
    QuotaSnapshot,
    UsageRecord,
    WebhookSubscription,
)
from dlaas_platform_contracts.observability import (
    ExplainTrace,
    LifeBlueprint,
    ReadoutBundle,
    ReadoutView,
    SnapshotExportRequest,
)
from dlaas_platform_contracts.capability_profile import (
    CERT_FORMULA_VERSION,
    AxisScore,
    CapabilityAxisId,
    CapabilityProfileSpec,
    CapabilityReadoutInputs,
    ClaimedResume,
    ComposedCapability,
    ExperienceSummary,
    ProfileProvenanceTier,
    SkillScore,
    build_profile_from_composed,
    compose_capability_indices,
    display_index,
    grade_for,
    percentile_band_for,
)
from dlaas_platform_contracts.persona_market import (
    BPS_DENOMINATOR,
    DEFAULT_PLATFORM_FEE_BPS,
    DEFAULT_PROVIDER_SHARE_BPS,
    MarketplaceLedgerEntry,
    PersonaListingSpec,
    PersonaListingStatus,
    PersonaListingVisibility,
    PersonaMarketUsageEvent,
    PersonaPriceModel,
    PersonaProvenance,
    PersonaSubscriptionSpec,
    PersonaSubscriptionStatus,
    SettlementStatus,
    compute_revenue_split,
)
from dlaas_platform_contracts.persona_lifecycle import (
    INDUCTION_GATE_STAGES,
    LifecycleStageEvent,
    LifecycleTransitionError,
    PersonaLifecycleStage,
    PersonaTrainingLifecycle,
    REQUIRED_EVIDENCE_BY_STAGE,
    gate_summary_from_events,
    stage_order_index,
    validate_stage_advance,
)
from dlaas_platform_contracts.plugins import (
    HttpEndpoint,
    HttpPluginSpec,
    MCPPluginSpec,
    PluginKind,
    PluginManifest,
    compute_plugin_tool_policy_snapshot,
    merge_capability_whitelist,
)
from dlaas_platform_contracts.resources import (
    AssetSpec,
    CitationPolicy,
    ContractSpec,
    ContractStatus,
    CoveragePolicy,
    FocusPersonSpec,
    HandoffStatus,
    HandoffTicketSpec,
    IdentityLinkSpec,
    ReadinessReport,
    ShellKind,
    ShellSpec,
    TemplateActivationStatus,
    TemplateAssetLinkSpec,
    TemplateSpec,
    TemplateStatus,
    TemplateVersionSpec,
    TenantSpec,
)
from dlaas_platform_contracts.training import (
    ProtocolSubmission,
    ProtocolSubmissionSourceType,
    TrainingJob,
    TrainingJobStatus,
    TrainingJobType,
)
from dlaas_platform_contracts.third_party_llm import (
    ThirdPartyLlmError,
    ThirdPartyLlmErrorCode,
    ThirdPartyLlmJsonRequest,
    ThirdPartyLlmJsonResponse,
    ThirdPartyLlmProvider,
    ThirdPartyLlmStatus,
)

__all__ = (
    "ANGLE_STAGE_ORDER",
    "AdoptionConfig",
    "ApplicationApprovalSpec",
    "ApplicationSpec",
    "ArtifactKind",
    "BakeAngle",
    "BakeAngleJob",
    "BakeAngleKind",
    "BakeAngleResult",
    "BakeAngleStatus",
    "BakeContractError",
    "BakeRequest",
    "BakeRun",
    "BakeRunEvent",
    "BakeRunStatus",
    "RawMaterial",
    "VALID_CORPUS_MODES",
    "VALID_RAW_MATERIAL_KINDS",
    "angle_stage_index",
    "is_terminal_angle_status",
    "is_terminal_run_status",
    "rollup_run_status",
    "AxisScore",
    "CERT_FORMULA_VERSION",
    "CapabilityAxisId",
    "CapabilityProfileSpec",
    "CapabilityReadoutInputs",
    "ClaimedResume",
    "ComposedCapability",
    "ExperienceSummary",
    "ProfileProvenanceTier",
    "SkillScore",
    "build_profile_from_composed",
    "compose_capability_indices",
    "display_index",
    "grade_for",
    "percentile_band_for",
    "BPS_DENOMINATOR",
    "DEFAULT_PLATFORM_FEE_BPS",
    "DEFAULT_PROVIDER_SHARE_BPS",
    "MarketplaceLedgerEntry",
    "PersonaMarketUsageEvent",
    "PersonaPriceModel",
    "SettlementStatus",
    "compute_revenue_split",
    "CAPABILITY_EXPERIENCE_BINDING",
    "EXPERIENCE_BRIEF_SCHEMA_VERSION",
    "EXPERIENCE_RECEIPT_SCHEMA_VERSION",
    "EXPERIENCE_REFLECTION_SCHEMA_VERSION",
    "ExperienceBriefSpec",
    "ExperienceBudgetHint",
    "ExperienceDomainBinding",
    "ExperienceReceiptSpec",
    "ExperienceReflectionSpec",
    "MARKETING_EXPERIENCE_BINDING",
    "MEMORIAL_EXPERIENCE_BINDING",
    "READER_DIALOGUE_EXPERIENCE_BINDING",
    "builtin_experience_domain_bindings",
    "find_binding_for_brief_kind",
    "is_experience_observation",
    "ArtifactRecord",
    "AssetIntakeDecision",
    "AssetIntakeIntent",
    "AssetIntakeRequest",
    "AssetMediaKind",
    "AssetSpec",
    "AuditEvent",
    "AudienceProfileSpec",
    "BillingEvent",
    "CitationPolicy",
    "CommandName",
    "ConsentRecord",
    "ContractSpec",
    "ContractStatus",
    "CoveragePolicy",
    "DataExportJob",
    "DataJobStatus",
    "DeletionJob",
    "DebugAnalysisReport",
    "DebugAnalysisRequest",
    "DebugAppRegistration",
    "DebugEventEnvelope",
    "DebugFieldDefinition",
    "DebugFieldOwner",
    "DebugFieldType",
    "DebugPrivacyLevel",
    "DebugSchema",
    "DebugVersionSuggestion",
    "EvalGateDecision",
    "EvalRun",
    "EvalRunStatus",
    "DEFAULT_PROTOCOL_VERSION",
    "ExamQuestionSpec",
    "ExamRunSpec",
    "ExamRunStatus",
    "ExamSubmissionScore",
    "EventStreamRecord",
    "EvidenceTrace",
    "ExplainTrace",
    "FeedbackPayload",
    "FeedbackValence",
    "FocusPersonSpec",
    "HandoffStatus",
    "HandoffTicketSpec",
    "HttpEndpoint",
    "HttpPluginSpec",
    "IdentityLinkSpec",
    "InstanceLifecycleState",
    "InstanceStatus",
    "InteractionEnvelope",
    "InteractionMode",
    "InteractionType",
    "InterviewRunSpec",
    "InterviewRunStatus",
    "InterviewTurn",
    "InterviewerKind",
    "LaunchLicenseSpec",
    "LifeBlueprint",
    "MCPPluginSpec",
    "MemoryPolicySelection",
    "ObservationType",
    "OpsPolicySelection",
    "OutputAct",
    "OutputContract",
    "INDUCTION_GATE_STAGES",
    "LifecycleStageEvent",
    "LifecycleTransitionError",
    "PersonaLifecycleStage",
    "PersonaListingSpec",
    "PersonaListingStatus",
    "PersonaListingVisibility",
    "PersonaProvenance",
    "PersonaSubscriptionSpec",
    "PersonaSubscriptionStatus",
    "PersonaTrainingLifecycle",
    "REQUIRED_EVIDENCE_BY_STAGE",
    "gate_summary_from_events",
    "stage_order_index",
    "validate_stage_advance",
    "PluginKind",
    "PluginManifest",
    "PolicySnapshot",
    "ProtocolSelection",
    "ProtocolSubmission",
    "ProtocolSubmissionSourceType",
    "PromotionDecision",
    "QuotaSnapshot",
    "ReadinessReport",
    "ReadoutBundle",
    "ReadoutView",
    "RubricEntry",
    "ShellKind",
    "ShellSpec",
    "SleepRequest",
    "SnapshotExportRequest",
    "SubstrateSelection",
    "TemplateActivationStatus",
    "TemplateAssetLinkSpec",
    "TemplateSpec",
    "TemplateStatus",
    "TemplateVersionSpec",
    "TenantSpec",
    "ThirdPartyLlmError",
    "ThirdPartyLlmErrorCode",
    "ThirdPartyLlmJsonRequest",
    "ThirdPartyLlmJsonResponse",
    "ThirdPartyLlmProvider",
    "ThirdPartyLlmStatus",
    "ToolPolicySelection",
    "TrainingJob",
    "TrainingJobStatus",
    "TrainingJobType",
    "TrainingPolicySelection",
    "UsageRecord",
    "VerticalSelection",
    "WakeRequest",
    "WebhookSubscription",
    "compute_plugin_tool_policy_snapshot",
    "feedback_valence_to_outcome_kind",
    "merge_capability_whitelist",
)
